# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20170312_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
