# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='expire_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
