# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20170414_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
