# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20170418_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='latitud',
            new_name='latitude',
        ),
    ]
