# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20170501_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPagaCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpaga_id', models.IntegerField()),
                ('token', models.CharField(blank=True, max_length=300, unique=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
    ]
