# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_auto_20170819_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpagacustomer',
            name='credit_card_id',
            field=models.CharField(blank=True, max_length=300, unique=True),
        ),
    ]
