# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-19 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_auto_20170902_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_id', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('card_holder_name', models.CharField(blank=True, max_length=300, null=True)),
                ('last_four', models.IntegerField()),
                ('type', models.CharField(choices=[('VISA', 'VISA'), ('MASTERCARD', 'MASTERCARD'), ('AMEX', 'AMEX'), ('DINERS', 'DINERS')], default='ORDERED', max_length=20)),
                ('tpagaCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.TPagaCustomer')),
            ],
        ),
    ]
