# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20170422_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtoken',
            name='token',
            field=models.TextField(unique=True),
        ),
    ]
