# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 11:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20170422_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
