# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-21 14:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20170830_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
