# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worktype', '0001_initial'),
        ('customer', '0003_auto_20170312_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('worktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worktype.WorkType')),
            ],
        ),
    ]
