# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_auto_20170414_1450'),
        ('work', '0003_work_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worker.Worker'),
        ),
    ]
