# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_work_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='asap',
            field=models.BooleanField(default=True),
        ),
    ]
