# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_dynamicpricing_multipliers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamicpricing',
            old_name='multipliers',
            new_name='multiplier',
        ),
    ]
