# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_auto_20170422_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicpricing',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='dynamicpricing',
            name='start',
            field=models.TimeField(),
        ),
    ]
