# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_auto_20170422_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='state',
            field=models.CharField(choices=[('ORDERED', 'ORDERED'), ('SCHEDULED', 'SCHEDULED'), ('FINISHED', 'FINISHED'), ('FAILED', 'FAILED'), ('CANCELED', 'CANCELED'), ('IN_PROGRESS', 'IN PROGRESS')], default='ORDERED', max_length=20),
        ),
    ]
