# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-15 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_remove_tpagacustomer_credit_card_id'),
        ('work', '0012_auto_20170903_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField(auto_now=True)),
                ('receipt_number', models.IntegerField(unique=True)),
                ('value', models.IntegerField()),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.CreditCard')),
                ('work', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.Work')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('item_type', models.CharField(choices=[('SERVICE', 'SERVICE'), ('IVA', 'IVA'), ('SUBTOTAL', 'SUBTOTAL'), ('SUPPLY', 'SUPPLY'), ('TOTAL', 'TOTAL')], default='SERVICE', max_length=20)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Transaction')),
            ],
        ),
    ]
