# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-15 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0014_transactionitem_bill_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('CREATING', 'CREATING'), ('CHARGE', 'CHARGE'), ('ROLLBACKED', 'ROLLBACKED')], default='CREATING', max_length=20),
        ),
    ]
