# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-15 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_transaction_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionitem',
            old_name='transaction',
            new_name='trx',
        ),
    ]
