# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-21 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0020_auto_20171021_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='third_party_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
