# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktype',
            name='icon',
            field=models.ImageField(upload_to=''),
        ),
    ]
