# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktype', '0002_auto_20170412_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('publications', models.ManyToManyField(to='worktype.WorkType')),
            ],
        ),
    ]
