# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktype', '0004_auto_20170412_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='worktype',
            name='price_type',
            field=models.CharField(choices=[('STANDARIZED', 'STANDARIZED'), ('NOT_STANDARIZED', 'NOT_STANDARIZED')], default='ORDERED', max_length=40),
        ),
    ]
