# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktype', '0005_auto_20170412_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='price_type',
            field=models.CharField(choices=[('STANDARIZED', 'STANDARIZED'), ('NOT_STANDARIZED', 'NOT_STANDARIZED'), ('UNKNOWN', 'UNKNOWN')], default='ORDERED', max_length=40),
        ),
    ]
