# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktype', '0006_auto_20170413_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worktype',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
