# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktype', '0007_auto_20170416_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worktype',
            options={'ordering': ['-order'], 'verbose_name': 'WorkType', 'verbose_name_plural': 'WorkTypes'},
        ),
    ]
