# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktype', '0008_auto_20170416_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-order'], 'verbose_name': 'WorkTypeCategory', 'verbose_name_plural': 'WorkTypeCategories'},
        ),
        migrations.AddField(
            model_name='worktype',
            name='url_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
