# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktype', '0009_auto_20170505_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'WorkTypeCategory', 'verbose_name_plural': 'WorkTypeCategories'},
        ),
        migrations.AlterField(
            model_name='worktype',
            name='price',
            field=models.IntegerField(default=-1),
        ),
    ]
