# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0002_work_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.Work')),
            ],
        ),
    ]
