# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 03:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worktype', '0006_auto_20170413_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, unique=True)),
                ('document_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('rh', models.CharField(blank=True, max_length=10)),
                ('profile_pic', models.ImageField(null=True, upload_to='workers/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('works', models.ManyToManyField(to='worktype.WorkType')),
            ],
        ),
    ]
